from setuptools import setup

print('setup kiki ...')
setup(
    name='kiki',
    version='0.0.1',
    author='crom',
    author_email='crom@zzizily.com',
    description='ZZiZiLY Commons Project',
    url='https://github.com/deuxksy/kiki',
    install_requires=[
        'aiohttp',
        'appdirs',
        'async-timeout',
        'chardet',
        'colorama',
        'decorator',
        'ipython',
        'ipython-genutils',
        'multidict',
        'packaging',
        'pickleshare',
        'pip',
        'prompt-toolkit',
        'psycopg2',
        'Pygments',
        'PyMySQL',
        'pyparsing',
        'redis',
        'requests',
        'setuptools',
        'simplegeneric',
        'six',
        'slacker',
        'telepot',
        'traitlets',
        'urllib3',
        'wcwidth',
        'wheel',
        'win-unicode-console',
        'yarl',
    ],
)
